name: whatsapp_clone
description: "A WhatsApp Clone built using Flutter and Firebase."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  emoji_picker_flutter: ^3.1.0
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  riverpod: ^2.6.1
  sqflite: ^2.4.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/user-icon.jpg
    - assets/images/meta-ai.png
    - assets/images/splash.png

  fonts:
    - family: Helvatica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: fonts/Helvetica-BoldOblique.ttf
          weight: 700
        - asset: fonts/helvetica-light-587ebe5a59211.ttf
        - asset: fonts/Helvetica-Oblique.ttf
        - asset: fonts/helvetica-rounded-bold-5871d05ead8de.otf
          weight: 700