// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCNyGtZtmsajrm_unRjzGW5VXsJH8KHM',
    appId: '1:151415949274:web:d2b4291ed8c475cfa362e3',
    messagingSenderId: '151415949274',
    projectId: 'whatsapp-clone-3ee5f',
    authDomain: 'whatsapp-clone-3ee5f.firebaseapp.com',
    storageBucket: 'whatsapp-clone-3ee5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFb8lUY_ZkZywObEKqzATft7-rJl5Nf2g',
    appId: '1:151415949274:android:bd1d70dd8a59bdbca362e3',
    messagingSenderId: '151415949274',
    projectId: 'whatsapp-clone-3ee5f',
    storageBucket: 'whatsapp-clone-3ee5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxuQ4_bmJ1Wmj6VprDxVYpYPbngwWI7gQ',
    appId: '1:151415949274:ios:6ca9eb9e5e3d4c8ea362e3',
    messagingSenderId: '151415949274',
    projectId: 'whatsapp-clone-3ee5f',
    storageBucket: 'whatsapp-clone-3ee5f.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxuQ4_bmJ1Wmj6VprDxVYpYPbngwWI7gQ',
    appId: '1:151415949274:ios:6ca9eb9e5e3d4c8ea362e3',
    messagingSenderId: '151415949274',
    projectId: 'whatsapp-clone-3ee5f',
    storageBucket: 'whatsapp-clone-3ee5f.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOCNyGtZtmsajrm_unRjzGW5VXsJH8KHM',
    appId: '1:151415949274:web:c61f68a53151ed52a362e3',
    messagingSenderId: '151415949274',
    projectId: 'whatsapp-clone-3ee5f',
    authDomain: 'whatsapp-clone-3ee5f.firebaseapp.com',
    storageBucket: 'whatsapp-clone-3ee5f.appspot.com',
  );

}